In [4]:
from sklearn.datasets import make_blobs
import numpy as np
from sklearn.decomposition import PCA

In [24]:
# centers = [[1, 1], [-1, -1]]
centers = [[0, 1, 2, 3, 4]]
# centers = [[1, 1, 1, 1], [-1, -1, -1, -1]]
total_no_samples = 10
cluster_std = 0.4
X, X_labels_true = make_blobs(n_samples=total_no_samples, n_features=5, 
                            centers=centers, 
                            cluster_std=cluster_std, random_state=0)
X

array([[ 0.05761743,  1.5817094 ,  2.30441509,  3.04867001,  4.17754529],
       [-1.02119593,  1.26144744,  2.34577448,  2.70313399,  4.90790185],
       [ 0.06197897,  1.15126501,  1.6448857 ,  2.20768141,  3.86083514],
       [ 0.13346973,  1.59763163,  1.91793669,  3.12522708,  3.6583617 ],
       [-0.17522972,  0.49888186,  2.31099614,  2.35444086,  3.91490389],
       [-0.39091115,  1.38003537,  1.93945712,  2.95871246,  4.1642394 ],
       [ 0.70562094,  1.16006288,  2.39149519,  3.89635728,  4.7470232 ],
       [-0.41942119,  0.43199283,  1.31749192,  3.78031016,  3.79613913],
       [-0.58174627,  1.01830341,  1.92512646,  3.61311169,  4.58774351],
       [ 0.06253959,  1.49211627,  2.48095194,  2.84506927,  3.8790789 ]])

In [39]:
 # pca, dataset_pca = perform_PCA(dimension_pca, dataset)
VARIANCE = 0.6
pca = PCA(VARIANCE)
dataset_pca = pca.fit_transform(X)
dataset_pca

array([[-0.02185635, -0.49280755],
       [-0.25780761,  0.43644926],
       [-0.82387255, -0.00294642],
       [-0.07535009, -0.39382822],
       [-0.69243704,  0.23876489],
       [-0.13698234,  0.09376515],
       [ 1.07351508, -0.72739676],
       [ 0.63398169,  0.92240679],
       [ 0.60733597,  0.46078575],
       [-0.30652676, -0.53519289]])

In [44]:
generated_spikes = np.random.uniform(low=dataset_pca.min(axis=0),
                                        high=dataset_pca.min(axis=0),
                                        size=(1, dataset_pca.shape[1]))
                                             # size=(no_of_spikes*induce, dimension_pca))
generated_spikes

array([[-0.82387255, -0.72739676]])

In [27]:
spikes = pca.inverse_transform(generated_spikes)
spikes

array([[0.14584211, 1.2431836 , 2.12952716, 3.71906052, 4.3870595 ]])

In [45]:
type(spikes)

numpy.ndarray

In [46]:
spikes.shape

(1, 5)

In [47]:
res = [np.array([[ 0.95029728,  0.99916205],
       [-0.97764367, -1.0006545 ]]), np.array([[1.67762716, 1.62089704]])]

In [52]:
np.array(res)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [63]:
np.concatenate(res, axis=0)

array([[ 0.95029728,  0.99916205],
       [-0.97764367, -1.0006545 ],
       [ 1.67762716,  1.62089704]])

In [57]:
res[0]

array([[ 0.95029728,  0.99916205],
       [-0.97764367, -1.0006545 ]])

In [59]:
res[1]

array([[1.67762716, 1.62089704]])