In [12]:
from sklearn.metrics.cluster import contingency_matrix
import numpy as np

In [28]:
labels_true = np.array([1, 0, 1, 1, 2, 2, 0,  0, 2, 2])
labels_pred = np.array([0, 1, 0, 0, 2, 2, 1, -1, 2, 2])

Build a contingency matrix describing the relationship between labels.

In [29]:
matrix = contingency_matrix(labels_true, labels_pred)
matrix

array([[1, 0, 2, 0],
       [0, 3, 0, 0],
       [0, 0, 0, 4]], dtype=int64)

Matrix C such that Cij is the number of samples in true class i and in predicted class j. 
In this example, columns have labels [-1, 0, 1, 2]

In [30]:
# delete -1 label, as DBSCAN/K-means consider it as outlier anyway
matrix = matrix[:, 1:]
matrix

array([[0, 2, 0],
       [3, 0, 0],
       [0, 0, 4]], dtype=int64)

In [31]:
labels_new = np.full_like(labels_pred, -1)
labels_new

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [32]:
np.max(matrix, axis=1)

array([2, 3, 4], dtype=int64)

In [33]:
row = np.argmax(np.max(matrix, axis=1))
row

2

In [36]:
value = np.max(np.max(matrix, axis=1))
value

4

In [35]:
col = np.argmax(matrix[row])
col

2

In [23]:
matrix

array([[0, 2, 0],
       [3, 0, 0],
       [0, 0, 4]], dtype=int64)

In [37]:
labels_pred[labels_pred == col]

array([2, 2, 2, 2])

In [26]:
matrix[row, col]

4

In [38]:
########### stop

In [40]:
from sklearn.metrics.cluster import adjusted_rand_score
from sklearn.metrics import f1_score

In [41]:
f1_score(labels_true, labels_pred, average='micro')

0.4000000000000001

In [42]:
adjusted_rand_score(labels_true, labels_pred)

0.88

In [43]:
########## BOOOOM